### PR TITLE
removed string constructor and formatter for Date Only fields

### PR DESCRIPTION
**Pull request by david-gibbs-ig**
These changes are to revert the generation of a new String constructor for Fields derived from UTCLocalDate

### CODE REVIEW

**Comment by david-gibbs-ig** [comment]
@crjohn - this is a pre-requisite to remove the string constructor in fields derived from UtcDateOnlyField, thanks

**Comment by chrjohn** [comment]
Sorry @david-gibbs-ig , could you please briefly explain what this change was needed for? Why does the constructor need to be removed?

**Comment by david-gibbs-ig** [comment]
I think it is easiest explain if I start the explanation with  where I went wrong. 
MessageTest.java has tests that use "TradeDate". See line 1551 on MessageTest in master. TradeDate should be of type "LocalMktDate". 

The new code generator treats LocalMktDate the same as UTCDateOnly (I'll come back to this), the legacy code generator treated them as Strings. 

The test used a string input, I was being careful about changing tests so I updated the code generator to accept String inputs for  the constructor. You noticed this and commented on it in the QuickFIX/J PR. I agree that the Formatter and String ctor are undesirable. It makes more sense to update the API and tests if we are preparing a 3.0 release. "LocalData.of(---)" is a much better API than accepting Strings.

image

image

@@ -848,8 +849,11 @@ public class MessageTest {
          * Prepare a very simple TradeCaptureReport message template and two
          * legs.
          */
-        Message tcr = new TradeCaptureReport(new TradeReportID("ABC1234"), new PreviouslyReported(
-                false), new LastQty(1000), new LastPx(5.6789), new TradeDate("20140101"),

It makes more sense and is safer like this.
+        Message tcr = new TradeCaptureReport(new TradeReportID("ABC1234"),
+                new PreviouslyReported(false),
+                new LastQty(1000),
+                new LastPx(5.6789),
+                new TradeDate(LocalDate.of(2014,1,1)),

Looking at this again what I think we should do is:

- create a new base class in quickfixj-base called "LocalMktDateField" (basically the same as "UTCDateOnlyField")
- update the code generator(s) to extend class LocalMktDateField for fields of type "LocalMktDate", rather than UTCDateOnlyField.

This would read better but give the same behaviour. 

If you are agree-able I'll update the code generator and quickfixj-base in the PR so you can see how it will look. I already updated the tests as above but have not pushed as the quickfixj-orchestra dependency is pre-requisite.

This change would not be backward compatible but it would be consistent and correct. For backward compatibility I could put the String ctor and ISO formatter back in - but this time for LocalMktDateField only. Or we could stick with the LocalDate ctor argument only. I think String ctor and ISO formatter can make sense for a LocalMktDateField than UTCDateOnlyField . I think this would be better than having more complicated code generation options. What do you think?

**Comment by david-gibbs-ig** [comment]
I can actually start testing that now if you want to try it. I've unit tested a quickfixj-base LocalMktDateField.java .

The same question applies for "LocalMktTime" but I will leave that for a minute.

image

**Comment by david-gibbs-ig** [comment]
@chrjohn Don't merge anything yet, I've got more to show once I see that it works with the QFJ build.

**Comment by david-gibbs-ig** [comment]
@chrjohn  I spent a while working through this and I think that it is only safe to map LocalMktTime and LocalMktDate to QFJ String datatypes.

**Pull request closed without merging**
